# Generated by Django 2.1 on 2019-01-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardviews', '0002_auto_20190113_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
